name: untarest_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # --- SEMUA DEPENDENSI DIGABUNGKAN DI SINI ---
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  flutter_svg: ^2.2.0
  image_picker: ^1.2.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.5.3
  cloud_firestore: ^6.0.2
  http: ^1.5.0
  cloudinary_public: ^0.23.1
  intl: ^0.18.1 # Versi yang lebih stabil
  url_launcher: ^6.3.2
  path_provider: ^2.1.1
  firebase_storage: ^13.0.2
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/dummy_news/news.json
    - assets/local_meme_photos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 500
    - family: GabrielSans
      fonts:
        - asset: assets/fonts/GabrielSans-Trial-Black.woff2
        - asset: assets/fonts/GabrielSans-Trial-BlackItalic.woff2
        - asset: assets/fonts/GabrielSans-Trial-Bold.woff2
        - asset: assets/fonts/GabrielSans-Trial-BoldItalic.woff2
        - asset: assets/fonts/GabrielSans-Trial-Light.woff2
        - asset: assets/fonts/GabrielSans-Trial-LightItalic.woff2
        - asset: assets/fonts/GabrielSans-Trial-Medium.woff2
        - asset: assets/fonts/GabrielSans-Trial-MediumItalic.woff2
        - asset: assets/fonts/GabrielSans-Trial-Normal.woff2
        - asset: assets/fonts/GabrielSans-Trial-Thin.woff2
