// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfJZY_uoKFj_dClukl5pYCQ8ytk5xMvis',
    appId: '1:626076073153:web:fa02d039626cd1ee432840',
    messagingSenderId: '626076073153',
    projectId: 'untarest-firebase-app',
    authDomain: 'untarest-firebase-app.firebaseapp.com',
    storageBucket: 'untarest-firebase-app.firebasestorage.app',
    measurementId: 'G-JXSECFXFD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFOHUGbpGMP2iBfY7TgLoNlHOu49DeCQ8',
    appId: '1:626076073153:android:44fb9348aa9b867c432840',
    messagingSenderId: '626076073153',
    projectId: 'untarest-firebase-app',
    storageBucket: 'untarest-firebase-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSs96k2W_1aiU_ngSA1l1SadMnOoEutvw',
    appId: '1:626076073153:ios:664949bd8970516c432840',
    messagingSenderId: '626076073153',
    projectId: 'untarest-firebase-app',
    storageBucket: 'untarest-firebase-app.firebasestorage.app',
    iosBundleId: 'com.example.untarestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSs96k2W_1aiU_ngSA1l1SadMnOoEutvw',
    appId: '1:626076073153:ios:664949bd8970516c432840',
    messagingSenderId: '626076073153',
    projectId: 'untarest-firebase-app',
    storageBucket: 'untarest-firebase-app.firebasestorage.app',
    iosBundleId: 'com.example.untarestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfJZY_uoKFj_dClukl5pYCQ8ytk5xMvis',
    appId: '1:626076073153:web:82790775db5b7d4b432840',
    messagingSenderId: '626076073153',
    projectId: 'untarest-firebase-app',
    authDomain: 'untarest-firebase-app.firebaseapp.com',
    storageBucket: 'untarest-firebase-app.firebasestorage.app',
    measurementId: 'G-1GKDG52YF1',
  );
}
